name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run junit tests
        run: ./gradlew clean test --info --tests com.crm.prototype.MapperTests
      - name: Publish Test Report # https://github.com/marketplace/actions/junit-report-action
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '/home/runner/work/estore/estore/build/reports/tests/test/index.html'
      - name: Build with Gradle
        run: ./gradlew build